/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.nio.file.Path;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    /**
     * This method prints an error whenever it finds a line that doesn’t end in a semi-colon.
     *
     * @param path the path
     * @return the string
     */
    public String linter(Path path){

        return "";
    }
}
