/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {

    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final ByteArrayOutputStream errContent = new ByteArrayOutputStream();


    @Before
    public void setUpStreams() {
        System.setOut(new PrintStream(outContent));
        System.setErr(new PrintStream(errContent));
    }


    @Test
    public void diceRoll_testWithValueToReturnTrue(){
        Library diceRoll = new Library();

        int[] expectedOutput = new int[4];

        assertTrue("Test method passing in an input value should work",
                diceRoll.diceRoll(4).length == expectedOutput.length);
    }

    @Test
    public void containsDuplicates_testArrayNoDuplicates(){
        Library containsDuplicates = new Library();

        int[] inputArray = new int[]{4,5,6,7,8};

        assertTrue("Should return true with array with no duplicates",
                containsDuplicates.containsDuplicates(inputArray)== true);
    }

    @Test
    public void calculateAverage_testMethodReturnsAverageValue(){
        Library calculateAverage = new Library();

        int[] inputArray = new int[]{1,2,3,4,5}; //15

        assertTrue("The average for the input array is 3",
                calculateAverage.calculateAverage(inputArray) == 3);

    }

    @Test
    public void lowestAverage_testMethodReturnLowestAverage(){
        Library library = new Library();

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60}, // 441/7 = 63
                {57, 65, 65, 70, 72, 65, 51}, // 445/7 = 63.57
                {55, 54, 60, 53, 59, 57, 61}, // 399/7 = 57
                {65, 56, 55, 52, 55, 62, 57}  // 402/7 = 57.42
        };

        int [] expected = {55, 54, 60, 53, 59, 57, 61};

        assertArrayEquals("The returns average array should equal the expected",expected,
                library.lowestAverage(weeklyMonthTemperatures)  );
    }

   @Test
    public void weatherData_testMethod(){
       Library library = new Library();

       int[][] weeklyMonthTemperatures = {
               {66, 64, 58, 65, 71, 57, 60},
               {57, 65, 65, 70, 72, 65, 51},
               {55, 54, 60, 53, 59, 57, 61},
               {65, 56, 55, 52, 55, 62, 57}
       };

       library.weatherData(weeklyMonthTemperatures);

       assertEquals("The min temp is 51\n" +
               "The max temp is 72\n" +
               "Never Seen: 63\n" +
               "Never Seen: 67\n" +
               "Never Seen: 68\n" +
               "Never Seen: 69\n", outContent.toString() );
   }

   @Test
    public void tally_testToReturnMostVotesInTally(){
        Library library = new Library();

        List<String> votes = new ArrayList<>();

        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = library.tally(votes);

        assertTrue("The most tally is Bush", "Bush" == winner);
   }
}
